version: '3.10'

services:
  backend:
    #image: django-docker:0.0.1
    build: ./backend
    #command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
  frontend:
    build: ./frontend
    command: npm start
    ports:
      - 3000:3000